url: "https://lavanyavijayk.github.io/"
baseurl: ""

title: Lavanya Vijayakrishnan
email: lavanyavijayakrishnan@gmail.com
description: "Engineer of scalable systems and smart AI — from agentic RAG pipelines to distributed data platforms that run at cloud scale."

remote_theme: y7kim/agency-jekyll-theme

plugins:
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty
